@url = https://cuddly-guacamole-7vgw6j9vp73xg7p-8080.app.github.dev/filmes

GET {{url}}

### 

GET {{url}}/3

###
POST {{url}}
Content-Type: application/json

{
    "titulo": "Velozes e furioses",
    "idGenero": 4,
    "idsProdutoras": [1]
}

###
PUT {{url}}/1
Content-Type: application/json

{
    "titulo": "Harry Potter e a Pedra Filosofal",
    "idGenero": 1,
    "idsProdutoras": [1, 2]
}

###
DELETE {{url}}/2