@url = https://cuddly-guacamole-7vgw6j9vp73xg7p-8080.app.github.dev/generos

GET {{url}}

### 

GET {{url}}/1

###
POST {{url}}
Content-Type: application/json

{
    "nome": "Ação"
}

###
PUT {{url}}/1
Content-Type: application/json

{
    "nome": "Aventura"
}

###
DELETE {{url}}/1